"""extends product and user models

Revision ID: 7e1c92a0e372
Revises: ce4e26073964
Create Date: 2024-03-09 11:37:29.526046

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e1c92a0e372'
down_revision: Union[str, None] = 'ce4e26073964'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('author_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'product', 'user', ['author_id'], ['id'])
    op.add_column('user', sa.Column('is_staff', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_staff')
    op.drop_constraint(None, 'product', type_='foreignkey')
    op.drop_column('product', 'author_id')
    # ### end Alembic commands ###
